support opentracing API
bukalapak/go-mysql-driver pull request #11
Opened 2018-08-09 08:41 UTC by evo3cx

### Description
support opentracing API

### Checklist
- [ ] add support OpenTracing API
- [ ]  go-mysql-driver will trace every database operation using OpenTracing API.

2018-08-09 09:51 UTC, calvinaditya95 approved these changes

2018-08-10 03:45 UTC, indrasaputra requested changes

2018-08-10 03:45 UTC, indrasaputra commented on connection.go
> +	span     opentracing.Span // add span for tracer
imo, ga cocok naruh span ini di mysqlConn karena span bukan bagian dari mysqlConn. harusnya dia independent sih.

2018-08-10 03:45 UTC, indrasaputra commented on connection.go
> +	span     opentracing.Span // add span for tracer
span (lebih general lagi, tracing) itu imo bukan bagian dari suatu struct. tapi flow yg mengalir pada suatu function. jadinya dia seharusnya exist secara terpisah dari code yg berhubungan dgn business logic.

2018-08-10 06:26 UTC, evo3cx commented on connection.go
> +	span     opentracing.Span // add span for tracer
pikir saya, kenapa span di tambahkan ke `mysqlConn` karena biar jadi single reponsibiility dan terpusat pada method `writePacket` aja , karena 
 `go-mysql-driver` haya implement dari package `database/sql` lebih mudah jika semua nya di trace ketika `writiePacket` di jalankan.

saya liat di mysqlConn ada beberapa field yang berkaitan dengan context dan di luar kendali pada mysql, 

seperti field, field `watcher` itu menunggu chanel dari context deadline/timeout cmiww
``` go
watcher  chan<- mysqlContext
	closech  chan struct{}
	finished chan<- struct{}
```

https://github.com/bukalapak/go-mysql-driver/pull/11/files/1bb264b55d8a10a50e135cbb2fbce8a4959d4308#diff-8f8a79f3f89c69a28dd878de98384cf9R48

2018-08-10 08:41 UTC, indrasaputra commented on connection.go
> +	span     opentracing.Span // add span for tracer
kalo goalnya kayak gitu, kenapa ga ditaruh di `writePacket` aja bikin span nya? SRP terpenuhi dan mysqlConn ga terganggu.

terkait `watcher`, imo itu emg bagian dari proses bisnis dia sih. mysqlConn butuh tau kapan dia timeout untuk halt kerjaan dia. beda sama span. mysqlConn ga butuh span buat kerjaan dia. span lebih jadi kebutuhan lain yg nge-watch apa yg dikerjakan mysqlConn.

2018-08-10 10:23 UTC, reza-putra commented on connection.go
> +	span     opentracing.Span // add span for tracer
```
kalo goalnya kayak gitu, kenapa ga ditaruh di writePacket aja bikin span nya? SRP terpenuhi dan mysqlConn ga terganggu.
```
kenapa ga di taruh di writePacket karena dari package `database/sql` sendiri hanya beberapa method saja yang menerima context.Context (ada yang dapat mengirimkan context ada yang tidak), jadi harus ada fields yang meyimpan value context tersebut dan di gunakan ketika `writePacket`, atau cara lain paling di tambahkan paling di semua public method `go-mysql-driver`

2018-08-10 10:32 UTC, indrasaputra commented on connection.go
> +	span     opentracing.Span // add span for tracer
@evo3cx hoo I see. hmmm...
tapi kalau yg ditaruh mysqlConn sih imo itu bukan implementasi yg baik juga.
cuma karena changes lain lebih ribet, sepertinya ga masalah juga ditaruh di sana. asalkan concurrent safe yaa. saya lupa driver ini udah menjamin concurrent safe apa belom. perlu dicek juga apakah mendefinisikan span di mysqlConn ga mengganggu concurrent safe nya.

2018-08-10 10:52 UTC, evo3cx commented on connection.go
> +	span     opentracing.Span // add span for tracer
seharusnya sih compatible/safe concurrent soal nya cara itu mysqlConn nya per context

2018-08-10 10:52 UTC, evo3cx commented on connection.go
> +	span     opentracing.Span // add span for tracer
saya merge yah

2018-08-10 10:56 UTC, indrasaputra approved these changes

2018-08-13 06:23 UTC, merged